- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: Add github runner user
  ansible.builtin.user:
    name: github-runner

- name: Create runner directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory
    owner: github-runner # giving permissions to folder
    group: github-runner

- name: Download Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
    dest: /actions-runner
    remote_src: yes
    owner: github-runner
    group: github-runner

- name: Install libicu
  ansible.builtin.dnf:
    name: libicu
    state: installed

- name: Generate token
  ansible.builtin.shell: |
   gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/shivanandhan33/actions/runners/registration-token | jq .token
  register: token
  become_user: ec2-user

- name: Register runner
  ansible.builtin.shell: |
    ./config.sh --unattended --url https://github.com/shivanandhanOrg --token {{ token.stdout }}  --name {{ ansible_hostname }} --runnergroup Default
  become_user: github-runner
  args:
    chdir: /actions-runner
#  ignore_errors: yes

- name: copy service file
  ansible.builtin.copy:
    src: github-runner.service
    dest: /etc/systemd/system/github-runner.service

- name: start Runner service
  ansible.builtin.systemd_service:
    name: github-runner
    daemon-reload: yes
    enabled: yes
    state: restarted

#- name: Copy terraform repo
#  ansible.builtin.get_url:
#    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
#    dest: /etc/yum.repos.d/hashicorp.repo
#
#- name: Install terraform
#  ansible.builtin.dnf:
#    name: terraform
#    state: installed # installing to get terraform on github-runner

